version: "1"
services:
  web-app:
    container_name: charly-web
    build:
      context: /opt/stacks/charly/app/app/alpha # Remplacez par le chemin vers votre Dockerfile
    restart: unless-stopped
    ports:
      - 5000:5000
    labels:
      - traefik.enable=true
      - traefik.http.routers.chweb.rule=Host(`chweb.musubi.dev`)
      - traefik.http.routers.chweb.entrypoints=websecure
      - traefik.http.routers.chweb.tls=true
      - traefik.http.routers.chweb.tls.certresolver=letsencryptresolver
      - traefik.http.services.chweb.loadbalancer.server.port=5000
      - traefik.http.services.chweb.loadbalancer.healthcheck.path=/health # Facultatif, si vous avez un endpoint de santé
      - traefik.http.services.chweb.loadbalancer.healthcheck.interval=30s
      - traefik.http.services.chweb.loadbalancer.healthcheck.timeout=10s
networks:
  traefik:
    external: true